-- PilotIQ SQCDME — PostgreSQL / Supabase schema
create type sqcdme_axis as enum ('S','Q','C','D','M','E');
create type problem_status as enum ('nouveau','en_cours','bloque','a_valider','cloture');
create type action_status as enum ('a_faire','en_cours','bloque','termine','annule');
create table sectors (id uuid primary key default gen_random_uuid(), name text not null, stagnant_days int not null default 3);
create table teams (id uuid primary key default gen_random_uuid(), sector_id uuid references sectors on delete cascade, name text not null);
create table users (id uuid primary key references auth.users, team_id uuid references teams, full_name text not null, role text not null check(role in ('admin','sector_manager','team_leader','maintenance','quality','viewer')));
create table lines (id uuid primary key default gen_random_uuid(), sector_id uuid references sectors on delete cascade, code text not null unique, active boolean default true);
create table problems (id uuid primary key default gen_random_uuid(), title text not null, description text, sector_id uuid not null references sectors, line_id uuid references lines, sqcdme_category sqcdme_axis not null, priority smallint check(priority between 1 and 4), status problem_status not null default 'nouveau', owner_id uuid not null references users, created_at timestamptz not null default now(), due_date date not null, closed_at timestamptz, last_update timestamptz not null default now(), impact text not null, cause text, next_action text not null);
create unique index max_three_priorities_guard on problems(priority) where priority between 1 and 3 and status <> 'cloture';
create table actions (id uuid primary key default gen_random_uuid(), problem_id uuid references problems on delete set null, line_id uuid references lines, sqcdme_category sqcdme_axis, title text not null, owner_id uuid not null references users, created_at timestamptz default now(), due_date date not null, status action_status default 'a_faire', progress smallint default 0 check(progress between 0 and 100), comment text, updated_at timestamptz default now());
create table escalations (id uuid primary key default gen_random_uuid(), problem_id uuid not null references problems on delete cascade, destination text not null, reason text not null, escalated_by uuid references users, expected_response_at timestamptz, status text default 'ouverte', comment text, created_at timestamptz default now());
create table sqcdme_daily (id uuid primary key default gen_random_uuid(), sector_id uuid references sectors, line_id uuid references lines, day date not null, category sqcdme_axis not null, status text not null check(status in ('ok','vigilance','critique','non_renseigne')), score numeric, event text, comment text, owner_id uuid references users, unique(sector_id,line_id,day,category));
create table kpis (id uuid primary key default gen_random_uuid(), line_id uuid references lines, recorded_on date not null, trs numeric, availability numeric, performance numeric, quality numeric, stop_count int, stop_minutes int, scrap numeric, rework numeric, late_orders int, incidents int);
create table meetings (id uuid primary key default gen_random_uuid(), sector_id uuid references sectors, team_id uuid references teams, facilitator_id uuid references users, started_at timestamptz, ended_at timestamptz, minutes jsonb, report jsonb);
create table comments (id uuid primary key default gen_random_uuid(), problem_id uuid references problems on delete cascade, action_id uuid references actions on delete cascade, author_id uuid references users, body text not null, created_at timestamptz default now(), check(problem_id is not null or action_id is not null));
create table attachments (id uuid primary key default gen_random_uuid(), problem_id uuid references problems on delete cascade, comment_id uuid references comments on delete cascade, storage_path text not null, mime_type text, created_at timestamptz default now());
-- En production : activer RLS sur toutes les tables et filtrer via le secteur de l'utilisateur.
